In [1]:
import pandas as pd

In [4]:
from pycaret.clustering import setup, create_model, assign_model, plot_model, save_model, load_model, predict_model

In [5]:
df = pd.read_csv('atc_pre_departure_delays_2025.csv', sep=',')
df.head()

,YEAR,MONTH_NUM,MONTH_MON,FLT_DATE,APT_ICAO,APT_NAME,STATE_NAME,FLT_DEP_1,FLT_DEP_IFR_2,DLY_ATC_PRE_2,FLT_DEP_3,DLY_ATC_PRE_3
0,2025,1,JAN,2025-01-01,BIKF,Keflavik,Iceland,68,68.0,0.0,14.0,3.0
1,2025,1,JAN,2025-01-01,EBAW,Antwerp,Belgium,4,NaN,NaN,1.0,0.0
2,2025,1,JAN,2025-01-01,EBBR,Brussels,Belgium,216,216.0,154.0,154.0,104.0
3,2025,1,JAN,2025-01-01,EBCI,Charleroi,Belgium,94,94.0,0.0,87.0,58.0
4,2025,1,JAN,2025-01-01,EBLG,Liège,Belgium,17,NaN,NaN,1.0,0.0

In [6]:
len(df)

56775

In [8]:
s = setup(df, session_id=111)

In [9]:
s.dataset.head()

,YEAR,MONTH_NUM,MONTH_MON,FLT_DATE,APT_ICAO,APT_NAME,STATE_NAME,FLT_DEP_1,FLT_DEP_IFR_2,DLY_ATC_PRE_2,FLT_DEP_3,DLY_ATC_PRE_3
0,2025,1,JAN,2025-01-01,BIKF,Keflavik,Iceland,68,68.0,0.0,14.0,3.0
1,2025,1,JAN,2025-01-01,EBAW,Antwerp,Belgium,4,NaN,NaN,1.0,0.0
2,2025,1,JAN,2025-01-01,EBBR,Brussels,Belgium,216,216.0,154.0,154.0,104.0
3,2025,1,JAN,2025-01-01,EBCI,Charleroi,Belgium,94,94.0,0.0,87.0,58.0
4,2025,1,JAN,2025-01-01,EBLG,Liège,Belgium,17,NaN,NaN,1.0,0.0

In [10]:
s.dataset_transformed.head()

,YEAR,MONTH_NUM,MONTH_MON_JAN,MONTH_MON_FEB,MONTH_MON_MAR,MONTH_MON_APR,MONTH_MON_MAY,MONTH_MON_JUN,FLT_DATE_2025-01-01,FLT_DATE_2025-01-02,...,STATE_NAME_Serbia,STATE_NAME_Montenegro,STATE_NAME_Slovakia,STATE_NAME_Armenia,STATE_NAME_Georgia,FLT_DEP_1,FLT_DEP_IFR_2,DLY_ATC_PRE_2,FLT_DEP_3,DLY_ATC_PRE_3
0,2025.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,68.0,68.000000,0.000000,14.0,3.0
1,2025.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,4.0,164.247635,108.287683,1.0,0.0
2,2025.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,216.0,216.000000,154.000000,154.0,104.0
3,2025.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,94.0,94.000000,0.000000,87.0,58.0
4,2025.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,17.0,164.247635,108.287683,1.0,0.0

In [11]:
kmeans = create_model('kmeans', num_clusters=20)

In [12]:
df_with_clusters = assign_model(kmeans)
df_with_clusters

,YEAR,MONTH_NUM,MONTH_MON,FLT_DATE,APT_ICAO,APT_NAME,STATE_NAME,FLT_DEP_1,FLT_DEP_IFR_2,DLY_ATC_PRE_2,FLT_DEP_3,DLY_ATC_PRE_3,Cluster
0,2025,1,JAN,2025-01-01,BIKF,Keflavik,Iceland,68,68.0,0.0,14.0,3.0,Cluster 12
1,2025,1,JAN,2025-01-01,EBAW,Antwerp,Belgium,4,NaN,NaN,1.0,0.0,Cluster 10
2,2025,1,JAN,2025-01-01,EBBR,Brussels,Belgium,216,216.0,154.0,154.0,104.0,Cluster 3
3,2025,1,JAN,2025-01-01,EBCI,Charleroi,Belgium,94,94.0,0.0,87.0,58.0,Cluster 12
4,2025,1,JAN,2025-01-01,EBLG,Liège,Belgium,17,NaN,NaN,1.0,0.0,Cluster 10
...,...,...,...,...,...,...,...,...,...,...,...,...,...
56770,2025,6,JUN,2025-06-30,LYBE,Belgrade - Nikola Tesla,Serbia,166,NaN,NaN,NaN,NaN,Cluster 13
56771,2025,6,JUN,2025-06-30,LYPG,Podgorica,Montenegro,28,NaN,NaN,NaN,NaN,Cluster 0
56772,2025,6,JUN,2025-06-30,LZIB,Bratislava,Slovakia,36,34.0,0.0,NaN,NaN,Cluster 12
56773,2025,6,JUN,2025-06-30,UDYZ,Yerevan,Armenia,60,NaN,NaN,NaN,NaN,Cluster 13
56774,2025,6,JUN,2025-06-30,UGTB,Tbilisi,Georgia,74,NaN,NaN,NaN,NaN,Cluster 13

In [13]:
df_with_clusters["Cluster"].value_counts()

Cluster 0     19922
Cluster 10    17669
Cluster 13     6164
Cluster 12     4985
Cluster 3      3204
Cluster 8      1363
Cluster 15      694
Cluster 11      623
Cluster 14      514
Cluster 4       423
Cluster 2       349
Cluster 18      267
Cluster 6       227
Cluster 7       177
Cluster 17      109
Cluster 1        47
Cluster 16       18
Cluster 19       16
Cluster 5         2
Cluster 9         2
Name: Cluster, dtype: int64

In [14]:
plot_model(kmeans, plot='cluster')

In [15]:
save_model(kmeans, 'atc_pre_departure_delays_2025_pipeline', verbose=False)

(Pipeline(memory=FastMemory(location=C:\Users\patry\AppData\Local\Temp\joblib),
          steps=[('numerical_imputer',
                  TransformerWrapper(include=['YEAR', 'MONTH_NUM', 'FLT_DEP_1',
                                              'FLT_DEP_IFR_2', 'DLY_ATC_PRE_2',
                                              'FLT_DEP_3', 'DLY_ATC_PRE_3'],
                                     transformer=SimpleImputer())),
                 ('categorical_imputer',
                  TransformerWrapper(include=['MONTH_MON', 'FLT_DATE',
                                              'APT_ICAO', 'APT_NAME...
                                     transformer=SimpleImputer(strategy='most_frequent'))),
                 ('onehot_encoding',
                  TransformerWrapper(include=['MONTH_MON', 'FLT_DATE',
                                              'APT_ICAO', 'APT_NAME',
                                              'STATE_NAME'],
                                     transformer=OneHotEncoder(cols=['MONTH_MON',
                                                                     'FLT_DATE',
                                                                     'APT_ICAO',
                                                                     'APT_NAME',
                                                                     'STATE_NAME'],
                                                               handle_missing='return_nan',
                                                               use_cat_names=True))),
                 ('trained_model', KMeans(n_clusters=20, random_state=111))]),
 'atc_pre_departure_delays_2025_pipeline.pkl')

In [16]:
kmeans_pipeline = load_model('atc_pre_departure_delays_2025_pipeline')
kmeans_pipeline

Transformation Pipeline and Model Successfully Loaded

Pipeline(memory=FastMemory(location=C:\Users\patry\AppData\Local\Temp\joblib),
         steps=[('numerical_imputer',
                 TransformerWrapper(include=['YEAR', 'MONTH_NUM', 'FLT_DEP_1',
                                             'FLT_DEP_IFR_2', 'DLY_ATC_PRE_2',
                                             'FLT_DEP_3', 'DLY_ATC_PRE_3'],
                                    transformer=SimpleImputer())),
                ('categorical_imputer',
                 TransformerWrapper(include=['MONTH_MON', 'FLT_DATE',
                                             'APT_ICAO', 'APT_NAME...
                                    transformer=SimpleImputer(strategy='most_frequent'))),
                ('onehot_encoding',
                 TransformerWrapper(include=['MONTH_MON', 'FLT_DATE',
                                             'APT_ICAO', 'APT_NAME',
                                             'STATE_NAME'],
                                    transformer=OneHotEncoder(cols=['MONTH_MON',
                                                                    'FLT_DATE',
                                                                    'APT_ICAO',
                                                                    'APT_NAME',
                                                                    'STATE_NAME'],
                                                              handle_missing='return_nan',
                                                              use_cat_names=True))),
                ('trained_model', KMeans(n_clusters=20, random_state=111))])