In [1]:
from pycaret.classification import load_model, predict_model
import pandas as pd

In [2]:
model = load_model("classification_pipeline")

Transformation Pipeline and Model Successfully Loaded

In [3]:
df = pd.DataFrame([
    {"x": 2, "y": 8},
    {"X": 2, "y": 2},
    {"x": 1, "y": 1}
])

predict_model(model, data=df)

     x  y    X prediction_label  prediction_score
0  2.0  8  NaN                A            0.9860
1  NaN  2  2.0                B            1.0000
2  1.0  1  NaN                B            0.7591

In [4]:
def classify_data(df, predicted_column_name="kategoria"):
    model = load_model("classification_pipeline")
    df = predict_model(model, data=df)
    df = df.rename(columns={"prediction_label": predicted_column_name})

    return df

In [5]:
classify_data(pd.DataFrame([
    {"x": 2, "y": 8},
    {"X": 2, "y": 2},
    {"x": 1, "y": 1}
])
)

Transformation Pipeline and Model Successfully Loaded

     x  y    X kategoria  prediction_score
0  2.0  8  NaN         A            0.9860
1  NaN  2  2.0         B            1.0000
2  1.0  1  NaN         B            0.7591