In [9]:
from pycaret.clustering import load_model, predict_model
import pandas as pd

In [10]:
model = load_model("clustering_pipeline")

Transformation Pipeline and Model Successfully Loaded

In [11]:
df = pd.DataFrame([
    {"x": 200, "y": 350},
    {"X": 100, "y": 100},
    {"x": 300, "y": 300}
])

predict_model(model, data=df)

       x    y    Cluster
0  200.0  350  Cluster 0
1    NaN  100  Cluster 2
2  300.0  300  Cluster 1

In [12]:
def assign_data_to_cluster(df, predicted_column_name="grupa", cluster_mapping=None):
    model = load_model("clustering_pipeline")
    df = predict_model(model, data=df)
    if cluster_mapping:
        df["Cluster"] = df["Cluster"].map(cluster_mapping)

    df = df.rename(columns={"Cluster": predicted_column_name})
    return df

In [14]:
assign_data_to_cluster(
    df=pd.DataFrame([
        {"x": 200, "y": 350},
        {"X": 100, "y": 100},
        {"x": 300, "y": 300}
    ]),
    cluster_mapping={"Cluster  0": "A", "Cluster 1": "B", "Cluster 2": "C"}
)

Transformation Pipeline and Model Successfully Loaded

       x    y grupa
0  200.0  350   NaN
1    NaN  100     C
2  300.0  300     B